nginx:
    image: vanosg/brewpi_nginx
    container_name: nginx
    ports:
        - "80:80"
    hostname: nginx

fpm:
    image: vanosg/brewpi_fpm
    container_name: fpm
    volumes_from:
        - nginx
    hostname: fpm

brewpi:
    image: vanosg/brewpi:latest
    container_name: brewpi
    hostname: brewpi
    volumes_from:
        - data

data:
    image: vanosg/brewpi_data
    container_name: data
    hostname: data
