version: '2'
services:
  brewpi:
    image: vanosg/rpi-brewpi-omni:latest
    container_name: brewpi
    hostname: brewpi

######
# If you are running on an Arduino (not a Spark)
# remove the #s from in front of the following 
# two lines:
######

    environment:
        - system=$system
    devices:
        - "/dev/ttyACM0:/dev/ttyACM0"
        - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
        - 80:80
    volumes:
        - ~/brewpi-data:/brewpi

networks:
    default:
      driver: bridge
