version: '2'
services:
  nginx:
    image: vanosg/rpi-brewpi-nginx
    container_name: nginx
    ports:
        - "80:80"
    hostname: nginx
    volumes_from:
        - data
        - brewpi
    devices:
        - "/dev/ttyACM0:/dev/ttyACM0"
        - "/dev/ttyAMA0:/dev/ttyAMA0"

  fpm:
    image: vanosg/rpi-brewpi-fpm
    container_name: fpm
#    volumes_from:
#        - nginx
    hostname: fpm
    volumes_from:
        - data
        - nginx
        - brewpi
    devices:
        - "/dev/ttyACM0:/dev/ttyACM0"
        - "/dev/ttyAMA0:/dev/ttyAMA0"

  brewpi:
    image: vanosg/rpi-brewpi:latest
    container_name: brewpi
    hostname: brewpi
    volumes_from:
        - data
    devices:
        - "/dev/ttyACM0:/dev/ttyACM0"
        - "/dev/ttyAMA0:/dev/ttyAMA0"

  data:
    image: vanosg/rpi-brewpi-data
    container_name: data
    hostname: data

networks:
    default:
      driver: bridge
